development:
  store: bottleshop24.myshopify.com
  password: 1dff28c152622d3b870cdee405402173
  theme_id: "live"
  bucket_size: 40
  refill_rate: 2
  ignore_files:
    - "*.swp"
    - "*~"
    - "config/settings_data.json"

